# Generated by Django 2.1.5 on 2019-01-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=200)),
                ('title', models.TextField(default='none', max_length=200)),
                ('summary', models.TextField(default='none', max_length=500)),
                ('pub_date', models.DateTimeField(verbose_name='day published')),
            ],
        ),
    ]
