# Generated by Django 2.1.5 on 2019-01-29 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowapi', '0002_auto_20190127_0031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='summary',
            field=models.TextField(default='none', max_length=10000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default='none', max_length=5000),
        ),
    ]
