# Generated by Django 2.1.5 on 2019-02-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meowapi', '0004_auto_20190130_1953'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='img',
            field=models.CharField(default='none', max_length=200),
        ),
    ]
